using System.Reflection;
using System.Runtime.InteropServices;
[assembly: AssemblyTitle("PsyxCalc")]
[assembly: AssemblyDescription("An advanced version of System.Math(mscorlib)")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("PsyxAI")]
[assembly: AssemblyProduct("PsyxCalc")]
[assembly: AssemblyCopyright("Copyright ©  2018")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]
[assembly: ComVisible(false)]
[assembly: Guid("ca831039-0d19-4b93-9f20-9544ff6af356")]
[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.0.0.0")]
[assembly: System.CLSCompliant(true)]